import type { Exercise } from "@/types/domain";

type SeedExercise = Omit<Exercise, "createdAt" | "updatedAt">;
type SeedExerciseInput = Omit<SeedExercise, "repUnit"> & { repUnit?: SeedExercise["repUnit"] };

function ex(e: SeedExerciseInput): SeedExercise {
  return { repUnit: "reps", ...e };
}

// Ids are stable slugs so alternatives / the default program can reference them directly.
export const EXERCISE_SEED: SeedExercise[] = [
  // ---------------- CHEST ----------------
  ex({
    id: "ex_barbell_bench_press",
    name: "Barbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "front_delts"],
    equipment: ["barbell", "flat_bench"],
    movementType: "push",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Lie on a flat bench, grip the bar just wider than shoulder-width, lower it to your mid-chest, then press up until arms are extended.",
    formCues: ["Keep shoulder blades pulled back and down", "Feet flat on the floor, slight arch in lower back", "Lower under control, bar path slightly toward face"],
    commonMistakes: ["Bouncing the bar off the chest", "Flaring elbows to 90°", "Lifting hips off the bench"],
    alternativeExerciseIds: ["ex_dumbbell_bench_press", "ex_chest_press_machine", "ex_pushups"],
  }),
  ex({
    id: "ex_dumbbell_bench_press",
    name: "Dumbbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "front_delts"],
    equipment: ["dumbbell", "flat_bench"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Lie on a flat bench holding a dumbbell in each hand at chest level, press up until arms are extended, lower under control.",
    formCues: ["Let dumbbells travel slightly inward at the top", "Keep wrists stacked over elbows", "Control the descent, don't let elbows drop below bench line"],
    commonMistakes: ["Letting dumbbells drift too wide", "Using momentum on the way up"],
    alternativeExerciseIds: ["ex_chest_press_machine", "ex_barbell_bench_press", "ex_pushups"],
  }),
  ex({
    id: "ex_incline_barbell_press",
    name: "Incline Barbell Press",
    primaryMuscle: "upper_chest",
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["barbell", "incline_bench"],
    movementType: "push",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "On a 30–45° incline bench, lower the bar to your upper chest and press up until arms are extended.",
    formCues: ["Keep incline at 30–45°, steeper reduces chest involvement", "Bar path toward upper chest/collarbone", "Don't let elbows flare excessively"],
    commonMistakes: ["Setting the bench too steep (turns it into a shoulder press)", "Half reps at the top"],
    alternativeExerciseIds: ["ex_incline_dumbbell_press", "ex_incline_machine_press", "ex_dumbbell_bench_press"],
  }),
  ex({
    id: "ex_incline_dumbbell_press",
    name: "Incline Dumbbell Press",
    primaryMuscle: "upper_chest",
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["dumbbell", "incline_bench"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "On an incline bench, press a dumbbell in each hand from shoulder level to full extension above your upper chest.",
    formCues: ["Set bench to 30–45°", "Keep core braced, no excessive back arch", "Squeeze upper chest at the top"],
    commonMistakes: ["Bench angle too steep", "Dropping dumbbells too fast at the bottom"],
    alternativeExerciseIds: ["ex_incline_barbell_press", "ex_incline_machine_press"],
  }),
  ex({
    id: "ex_incline_machine_press",
    name: "Incline Chest Press Machine",
    primaryMuscle: "upper_chest",
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: ["chest_press_machine"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Set seat height so handles sit at upper-chest level, press forward and up until arms extend, return under control.",
    formCues: ["Adjust seat so handles align with upper chest", "Keep back flat against pad"],
    commonMistakes: ["Seat set too low, turning it into a mid-chest press"],
    alternativeExerciseIds: ["ex_incline_dumbbell_press", "ex_incline_barbell_press"],
  }),
  ex({
    id: "ex_chest_press_machine",
    name: "Chest Press Machine",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "front_delts"],
    equipment: ["chest_press_machine"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Set seat so handles are at mid-chest height, press forward until arms extend, return under control without locking out hard.",
    formCues: ["Back flat against the pad", "Full stretch at the back, don't slam the stack"],
    commonMistakes: ["Partial range of motion", "Shrugging shoulders up during the press"],
    alternativeExerciseIds: ["ex_dumbbell_bench_press", "ex_barbell_bench_press", "ex_pushups"],
  }),
  ex({
    id: "ex_pushups",
    name: "Push-ups",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "front_delts", "core"],
    equipment: ["bodyweight"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "bodyweight",
    repRangeMin: 10,
    repRangeMax: 20,
    recommendedSets: 3,
    restSeconds: 90,
    instructions: "Hands slightly wider than shoulders, lower chest to just above the floor keeping a straight line from head to heels, push back up.",
    formCues: ["Keep core and glutes braced", "Elbows at roughly 45° to torso"],
    commonMistakes: ["Sagging hips", "Only doing half reps"],
    alternativeExerciseIds: ["ex_dumbbell_bench_press", "ex_chest_press_machine"],
  }),
  ex({
    id: "ex_pec_deck_fly",
    name: "Pec Deck / Chest Fly Machine",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    equipment: ["pec_deck"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Sit with back flat against the pad, bring handles together in front of your chest in a hugging motion, return with control to a comfortable stretch.",
    formCues: ["Slight bend in elbows throughout", "Squeeze and pause briefly at the center"],
    commonMistakes: ["Using momentum to slam the handles together", "Overstretching shoulders at the back"],
    alternativeExerciseIds: ["ex_dumbbell_fly", "ex_cable_fly"],
  }),
  ex({
    id: "ex_dumbbell_fly",
    name: "Dumbbell Fly",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    equipment: ["dumbbell", "flat_bench"],
    movementType: "isolation",
    isCompound: false,
    level: "intermediate",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Lying on a flat bench with a slight elbow bend, lower dumbbells out to the sides in an arc, then bring them back together over your chest.",
    formCues: ["Keep the same slight elbow bend throughout", "Lead with the wrists, not the elbows"],
    commonMistakes: ["Going too heavy and turning it into a press", "Lowering too deep and straining the shoulder"],
    alternativeExerciseIds: ["ex_pec_deck_fly", "ex_cable_fly"],
  }),
  ex({
    id: "ex_cable_fly",
    name: "Cable Fly",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    equipment: ["cable_machine"],
    movementType: "isolation",
    isCompound: false,
    level: "intermediate",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Standing between two cable towers, pull the handles down and together in front of your chest in an arcing motion, return with control.",
    formCues: ["Slight forward lean, chest up", "Squeeze at the center of the movement"],
    commonMistakes: ["Using the arms/shoulders instead of chest to move the weight"],
    alternativeExerciseIds: ["ex_pec_deck_fly", "ex_dumbbell_fly"],
  }),

  // ---------------- TRICEPS ----------------
  ex({
    id: "ex_triceps_pushdown",
    name: "Cable Triceps Pushdown",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["cable_machine"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Grip the bar/rope at chest height, keep elbows pinned to your sides, extend arms down fully, return with control.",
    formCues: ["Elbows stay locked at your sides", "Full lockout at the bottom without shrugging"],
    commonMistakes: ["Letting elbows drift forward", "Using body weight/leaning to push the bar down"],
    alternativeExerciseIds: ["ex_overhead_triceps_extension", "ex_close_grip_bench", "ex_ez_bar_skullcrusher"],
  }),
  ex({
    id: "ex_overhead_triceps_extension",
    name: "Overhead Dumbbell Triceps Extension",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Hold one dumbbell overhead with both hands, lower it behind your head by bending the elbows, then extend back up.",
    formCues: ["Keep elbows pointed forward, close to your head", "Control the stretch at the bottom"],
    commonMistakes: ["Flaring elbows out wide", "Arching the lower back excessively"],
    alternativeExerciseIds: ["ex_triceps_pushdown", "ex_ez_bar_skullcrusher"],
  }),
  ex({
    id: "ex_close_grip_bench",
    name: "Close-Grip Barbell Bench Press",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "front_delts"],
    equipment: ["barbell", "flat_bench"],
    movementType: "push",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Grip the bar shoulder-width or slightly narrower, lower to your lower chest keeping elbows tucked, press back up.",
    formCues: ["Keep elbows tucked close to your torso", "Wrists stacked over elbows, not bent back"],
    commonMistakes: ["Gripping too narrow and straining wrists", "Flaring elbows out"],
    alternativeExerciseIds: ["ex_dips", "ex_triceps_pushdown"],
  }),
  ex({
    id: "ex_dips",
    name: "Triceps Dips",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "front_delts"],
    equipment: ["bodyweight"],
    movementType: "push",
    isCompound: true,
    level: "intermediate",
    loadType: "bodyweight",
    repRangeMin: 8,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 90,
    instructions: "Support yourself on parallel bars/bench, lower until upper arms are roughly parallel to the floor, press back up.",
    formCues: ["Keep torso fairly upright to bias triceps", "Control the descent"],
    commonMistakes: ["Going too deep and straining the shoulders", "Bouncing at the bottom"],
    alternativeExerciseIds: ["ex_close_grip_bench", "ex_triceps_pushdown"],
  }),
  ex({
    id: "ex_ez_bar_skullcrusher",
    name: "EZ Bar Skullcrusher",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["ez_curl_bar", "flat_bench"],
    movementType: "isolation",
    isCompound: false,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Lying on a flat bench holding the EZ bar above your chest, bend elbows to lower the bar toward your forehead, extend back up.",
    formCues: ["Keep upper arms vertical and still", "Lower under control to just above the forehead"],
    commonMistakes: ["Letting elbows flare or drift backward", "Using too much weight and losing control"],
    alternativeExerciseIds: ["ex_overhead_triceps_extension", "ex_triceps_pushdown"],
  }),

  // ---------------- BACK ----------------
  ex({
    id: "ex_lat_pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["lat_pulldown"],
    movementType: "pull",
    isCompound: true,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Grip the bar wider than shoulder-width, pull it down to your upper chest while leaning back slightly, control it back up to a full stretch.",
    formCues: ["Drive elbows down and back", "Chest up, slight backward lean, no swinging"],
    commonMistakes: ["Pulling behind the neck", "Using body momentum instead of the lats"],
    alternativeExerciseIds: ["ex_assisted_pullup", "ex_pullup", "ex_seated_cable_row"],
  }),
  ex({
    id: "ex_pullup",
    name: "Pull-up",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["pull_up_bar"],
    movementType: "pull",
    isCompound: true,
    level: "advanced",
    loadType: "bodyweight",
    repRangeMin: 6,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Hang from the bar with an overhand grip, pull yourself up until your chin clears the bar, lower with control to full arm extension.",
    formCues: ["Pull elbows down toward your hips", "Avoid kipping/swinging"],
    commonMistakes: ["Partial range of motion", "Using momentum instead of controlled pulling"],
    alternativeExerciseIds: ["ex_assisted_pullup", "ex_lat_pulldown"],
  }),
  ex({
    id: "ex_assisted_pullup",
    name: "Assisted Pull-up",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["pull_up_bar", "bodyweight"],
    movementType: "pull",
    isCompound: true,
    level: "beginner",
    loadType: "bodyweight",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Using a resistance band looped over the bar (or an assisted pull-up machine), pull yourself up until chin clears the bar, lower under control.",
    formCues: ["Keep the same pulling technique as a full pull-up", "Reduce assistance gradually over time"],
    commonMistakes: ["Relying entirely on the band/machine instead of pulling actively"],
    alternativeExerciseIds: ["ex_lat_pulldown", "ex_pullup"],
  }),
  ex({
    id: "ex_seated_cable_row",
    name: "Seated Cable Row",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts", "traps"],
    equipment: ["seated_cable_row"],
    movementType: "pull",
    isCompound: true,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Sit with knees slightly bent, grip the handle, pull it toward your lower abdomen while keeping your back straight, return with control.",
    formCues: ["Keep chest up, avoid rounding the back", "Pull with elbows, squeeze shoulder blades together"],
    commonMistakes: ["Rocking the torso back and forth for momentum", "Rounding the lower back"],
    alternativeExerciseIds: ["ex_barbell_row", "ex_dumbbell_row"],
  }),
  ex({
    id: "ex_barbell_row",
    name: "Barbell Row",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts", "traps"],
    equipment: ["barbell"],
    movementType: "pull",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Hinge at the hips with a flat back, pull the bar toward your lower ribcage, squeeze the back, lower with control.",
    formCues: ["Keep back flat, hinge from the hips", "Pull with elbows, not hands"],
    commonMistakes: ["Rounding the lower back", "Standing too upright and turning it into a shrug"],
    alternativeExerciseIds: ["ex_seated_cable_row", "ex_dumbbell_row"],
  }),
  ex({
    id: "ex_dumbbell_row",
    name: "One-Arm Dumbbell Row",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["dumbbell", "flat_bench"],
    movementType: "pull",
    isCompound: true,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Support one knee and hand on a bench, pull the dumbbell up toward your hip, squeeze the back, lower with control.",
    formCues: ["Keep back flat and roughly parallel to the floor", "Pull elbow up and back, not out to the side"],
    commonMistakes: ["Twisting the torso for momentum", "Using too short a range of motion"],
    alternativeExerciseIds: ["ex_seated_cable_row", "ex_barbell_row"],
  }),
  ex({
    id: "ex_straight_arm_pulldown",
    name: "Straight-Arm Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: [],
    equipment: ["cable_machine"],
    movementType: "isolation",
    isCompound: false,
    level: "intermediate",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 2,
    restSeconds: 75,
    instructions: "Standing, grip a straight bar attached high on the cable, keep arms straight and pull down to your thighs using your lats.",
    formCues: ["Keep a slight bend in the elbows, fixed throughout", "Hinge slightly forward from the hips"],
    commonMistakes: ["Bending the elbows to turn it into a pushdown"],
    alternativeExerciseIds: ["ex_lat_pulldown", "ex_seated_cable_row"],
  }),
  ex({
    id: "ex_face_pull",
    name: "Face Pull",
    primaryMuscle: "rear_delts",
    secondaryMuscles: ["traps"],
    equipment: ["cable_machine"],
    movementType: "pull",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Set a rope attachment at upper-chest height, pull it toward your face while flaring elbows out, squeezing rear delts and upper back.",
    formCues: ["Pull hands apart at the face, elbows high", "Keep core braced, avoid leaning back"],
    commonMistakes: ["Using too much weight and turning it into a row"],
    alternativeExerciseIds: ["ex_rear_delt_fly"],
  }),
  ex({
    id: "ex_rear_delt_fly",
    name: "Rear Delt Fly",
    primaryMuscle: "rear_delts",
    secondaryMuscles: ["traps"],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Hinge forward with a flat back, raise dumbbells out to the sides with a slight elbow bend, squeeze shoulder blades, lower with control.",
    formCues: ["Lead with the elbows, not the hands", "Keep a slight, fixed bend in the elbows"],
    commonMistakes: ["Standing too upright, shifting the work to traps", "Swinging the weights up"],
    alternativeExerciseIds: ["ex_face_pull"],
  }),

  // ---------------- BICEPS ----------------
  ex({
    id: "ex_barbell_curl",
    name: "Barbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["barbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "barbell",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Standing, grip the bar shoulder-width, curl it up to shoulder level keeping elbows pinned to your sides, lower with control.",
    formCues: ["Keep elbows locked at your sides", "Avoid swinging the torso"],
    commonMistakes: ["Using body momentum ('cheat curls')", "Only doing the bottom half of the rep"],
    alternativeExerciseIds: ["ex_ez_bar_curl", "ex_dumbbell_curl"],
  }),
  ex({
    id: "ex_ez_bar_curl",
    name: "EZ Bar Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["ez_curl_bar"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "barbell",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Grip the angled part of the EZ bar, curl up keeping elbows still, squeeze at the top, lower with control.",
    formCues: ["Wrists stay neutral thanks to the angled grip", "Keep elbows fixed at your sides"],
    commonMistakes: ["Swinging the bar up with the hips"],
    alternativeExerciseIds: ["ex_barbell_curl", "ex_dumbbell_curl"],
  }),
  ex({
    id: "ex_dumbbell_curl",
    name: "Dumbbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Standing or seated, curl each dumbbell up while keeping elbows at your sides, rotate palm up as you curl, lower with control.",
    formCues: ["Keep elbows still, close to your torso", "Squeeze biceps at the top"],
    commonMistakes: ["Swinging the weights using momentum", "Letting elbows drift forward"],
    alternativeExerciseIds: ["ex_ez_bar_curl", "ex_cable_curl"],
  }),
  ex({
    id: "ex_hammer_curl",
    name: "Hammer Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Hold dumbbells with a neutral (palms-facing-in) grip, curl up keeping elbows at your sides, lower with control.",
    formCues: ["Keep wrists neutral throughout", "Elbows fixed at your sides"],
    commonMistakes: ["Swinging the shoulders to generate momentum"],
    alternativeExerciseIds: ["ex_dumbbell_curl", "ex_cable_curl"],
  }),
  ex({
    id: "ex_cable_curl",
    name: "Cable Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["cable_machine"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Grip a straight or EZ attachment on a low pulley, curl up keeping elbows at your sides, lower with control against the constant tension.",
    formCues: ["Keep elbows fixed, close to torso", "Control the negative — don't let the stack drop"],
    commonMistakes: ["Leaning back to help the curl"],
    alternativeExerciseIds: ["ex_dumbbell_curl", "ex_ez_bar_curl"],
  }),

  // ---------------- SHOULDERS ----------------
  ex({
    id: "ex_shoulder_press_machine",
    name: "Shoulder Press Machine",
    primaryMuscle: "front_delts",
    secondaryMuscles: ["triceps", "lateral_delts"],
    equipment: ["shoulder_press_machine"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Sit with back against the pad, grip handles at shoulder height, press up until arms are extended, lower with control.",
    formCues: ["Keep back flat against the pad", "Don't lock elbows out aggressively"],
    commonMistakes: ["Arching the back excessively to press more weight"],
    alternativeExerciseIds: ["ex_dumbbell_shoulder_press", "ex_barbell_overhead_press"],
  }),
  ex({
    id: "ex_dumbbell_shoulder_press",
    name: "Dumbbell Shoulder Press",
    primaryMuscle: "front_delts",
    secondaryMuscles: ["triceps", "lateral_delts"],
    equipment: ["dumbbell"],
    movementType: "push",
    isCompound: true,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Seated or standing, press dumbbells from shoulder height straight overhead until arms extend, lower with control.",
    formCues: ["Keep core braced, avoid excessive back arch", "Press slightly inward at the top"],
    commonMistakes: ["Flaring elbows too far back", "Using leg drive to cheat the weight up"],
    alternativeExerciseIds: ["ex_shoulder_press_machine", "ex_barbell_overhead_press"],
  }),
  ex({
    id: "ex_barbell_overhead_press",
    name: "Barbell Overhead Press",
    primaryMuscle: "front_delts",
    secondaryMuscles: ["triceps", "lateral_delts"],
    equipment: ["barbell"],
    movementType: "push",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 6,
    repRangeMax: 10,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Standing, grip the bar just outside shoulder-width at collarbone height, press straight overhead until arms extend, lower with control.",
    formCues: ["Brace your core, squeeze glutes to protect the lower back", "Move your head back slightly so the bar passes close to your face"],
    commonMistakes: ["Excessive lower back arch", "Pressing the bar forward instead of straight up"],
    alternativeExerciseIds: ["ex_dumbbell_shoulder_press", "ex_shoulder_press_machine"],
  }),
  ex({
    id: "ex_dumbbell_lateral_raise",
    name: "Dumbbell Lateral Raise",
    primaryMuscle: "lateral_delts",
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Standing, raise dumbbells out to the sides with a slight elbow bend until roughly shoulder height, lower with control.",
    formCues: ["Lead with the elbows, not the hands", "Stop at shoulder height, don't shrug up"],
    commonMistakes: ["Using momentum/swinging", "Going too heavy and turning it into a shrug"],
    alternativeExerciseIds: ["ex_cable_lateral_raise"],
  }),
  ex({
    id: "ex_cable_lateral_raise",
    name: "Cable Lateral Raise",
    primaryMuscle: "lateral_delts",
    secondaryMuscles: [],
    equipment: ["cable_machine"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Stand side-on to a low pulley, raise the handle out and up to shoulder height with a slight elbow bend, lower with control.",
    formCues: ["Keep constant tension — don't let the weight rest at the bottom", "Lead with the elbow"],
    commonMistakes: ["Turning the torso to help lift the weight"],
    alternativeExerciseIds: ["ex_dumbbell_lateral_raise"],
  }),
  ex({
    id: "ex_front_raise",
    name: "Dumbbell Front Raise",
    primaryMuscle: "front_delts",
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 2,
    restSeconds: 60,
    instructions: "Standing, raise a dumbbell in each hand (or alternating) straight in front of you to shoulder height, lower with control.",
    formCues: ["Keep a slight elbow bend", "Avoid swinging the torso back"],
    commonMistakes: ["Raising above shoulder height and using the traps"],
    alternativeExerciseIds: ["ex_dumbbell_lateral_raise"],
  }),

  // ---------------- LEGS ----------------
  ex({
    id: "ex_barbell_squat",
    name: "Barbell Back Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "core"],
    equipment: ["barbell", "squat_rack"],
    movementType: "squat",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 6,
    repRangeMax: 10,
    recommendedSets: 3,
    restSeconds: 180,
    instructions: "Bar racked on your upper back, feet shoulder-width, squat down until thighs are at least parallel, drive back up through your heels.",
    formCues: ["Brace your core before descending", "Knees track over your toes", "Keep chest up throughout"],
    commonMistakes: ["Knees caving inward", "Not reaching sufficient depth", "Heels lifting off the floor"],
    alternativeExerciseIds: ["ex_smith_machine_squat", "ex_leg_press", "ex_goblet_squat"],
  }),
  ex({
    id: "ex_smith_machine_squat",
    name: "Smith Machine Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["smith_machine"],
    movementType: "squat",
    isCompound: true,
    level: "beginner",
    loadType: "barbell",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Bar on your upper back in the Smith rack, feet slightly forward of the bar path, squat down and drive back up.",
    formCues: ["Feet slightly ahead of the bar since the path is fixed vertical", "Keep chest up"],
    commonMistakes: ["Feet placed directly under the bar, causing an awkward path"],
    alternativeExerciseIds: ["ex_barbell_squat", "ex_leg_press"],
  }),
  ex({
    id: "ex_leg_press",
    name: "Leg Press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["leg_press"],
    movementType: "squat",
    isCompound: true,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Feet shoulder-width on the platform, lower it until knees reach roughly 90°, press back up without locking knees hard.",
    formCues: ["Keep lower back flat against the pad", "Don't let knees cave inward"],
    commonMistakes: ["Lowering too far and rounding the lower back", "Locking knees out hard at the top"],
    alternativeExerciseIds: ["ex_barbell_squat", "ex_smith_machine_squat", "ex_goblet_squat"],
  }),
  ex({
    id: "ex_goblet_squat",
    name: "Goblet Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbell"],
    movementType: "squat",
    isCompound: true,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 120,
    instructions: "Hold one dumbbell vertically at your chest, squat down between your knees keeping torso upright, drive back up.",
    formCues: ["Keep elbows brushing the inside of your knees at the bottom", "Chest up throughout"],
    commonMistakes: ["Leaning too far forward", "Rounding the upper back"],
    alternativeExerciseIds: ["ex_leg_press", "ex_barbell_squat"],
  }),
  ex({
    id: "ex_leg_extension",
    name: "Leg Extension",
    primaryMuscle: "quads",
    secondaryMuscles: [],
    equipment: ["leg_extension"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Sit with shin pad against your lower shins, extend legs until straight, squeeze quads, lower with control.",
    formCues: ["Point toes forward or slightly up", "Pause briefly at full extension"],
    commonMistakes: ["Using momentum to swing the weight up"],
    alternativeExerciseIds: ["ex_goblet_squat", "ex_leg_press"],
  }),
  ex({
    id: "ex_leg_curl",
    name: "Leg Curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: ["leg_curl"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 75,
    instructions: "Lying or seated, curl the pad toward your glutes by bending your knees, squeeze hamstrings, lower with control.",
    formCues: ["Keep hips pressed into the pad, don't lift them", "Full stretch at the bottom"],
    commonMistakes: ["Lifting hips to use momentum"],
    alternativeExerciseIds: ["ex_romanian_deadlift"],
  }),
  ex({
    id: "ex_romanian_deadlift",
    name: "Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
    movementType: "hinge",
    isCompound: true,
    level: "intermediate",
    loadType: "barbell",
    repRangeMin: 8,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 150,
    instructions: "Holding the bar in front of your thighs, hinge at the hips pushing them back, lower the bar along your legs to mid-shin, drive hips forward to stand.",
    formCues: ["Keep the bar close to your legs", "Maintain a flat back throughout", "Soft knee bend, not a squat"],
    commonMistakes: ["Rounding the lower back", "Squatting the weight down instead of hinging"],
    alternativeExerciseIds: ["ex_leg_curl"],
  }),
  ex({
    id: "ex_walking_lunge",
    name: "Walking Lunge",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["dumbbell"],
    movementType: "squat",
    isCompound: true,
    level: "intermediate",
    loadType: "dumbbell_each",
    repRangeMin: 10,
    repRangeMax: 12,
    recommendedSets: 3,
    restSeconds: 90,
    instructions: "Holding a dumbbell in each hand, step forward into a lunge until both knees reach roughly 90°, push through the front foot to step into the next lunge.",
    formCues: ["Keep torso upright", "Front knee tracks over the foot, not caving in"],
    commonMistakes: ["Taking too short a step, reducing range of motion"],
    alternativeExerciseIds: ["ex_leg_press", "ex_goblet_squat"],
  }),
  ex({
    id: "ex_calf_raise_machine",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["smith_machine", "leg_press"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 12,
    repRangeMax: 20,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Balls of feet on the edge of a platform, rise up onto your toes as high as possible, lower down into a full stretch.",
    formCues: ["Pause briefly at the top squeeze", "Get a full stretch at the bottom"],
    commonMistakes: ["Bouncing quickly instead of controlling the stretch"],
    alternativeExerciseIds: ["ex_dumbbell_calf_raise"],
  }),
  ex({
    id: "ex_dumbbell_calf_raise",
    name: "Dumbbell Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "dumbbell_each",
    repRangeMin: 12,
    repRangeMax: 20,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Holding dumbbells at your sides, stand on the balls of your feet on a raised surface, rise up as high as possible, lower into a full stretch.",
    formCues: ["Use a step or plate for extra range of motion", "Control the descent"],
    commonMistakes: ["Rushing the reps without a full stretch"],
    alternativeExerciseIds: ["ex_calf_raise_machine"],
  }),

  // ---------------- ABS / CORE ----------------
  ex({
    id: "ex_cable_crunch",
    name: "Cable Crunch",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["cable_machine"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "machine_stack",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Kneeling under a high pulley with a rope, crunch down by curling your torso toward your hips, using your abs not your arms.",
    formCues: ["Round your spine, don't just hinge at the hips", "Keep hips relatively still"],
    commonMistakes: ["Pulling with the arms instead of crunching with the abs"],
    alternativeExerciseIds: ["ex_hanging_leg_raise", "ex_plank"],
  }),
  ex({
    id: "ex_hanging_leg_raise",
    name: "Hanging Leg Raise",
    primaryMuscle: "core",
    secondaryMuscles: ["forearms"],
    equipment: ["pull_up_bar"],
    movementType: "isolation",
    isCompound: false,
    level: "intermediate",
    loadType: "bodyweight",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Hang from the bar, raise your legs (knees bent or straight) up toward your chest using your abs, lower with control.",
    formCues: ["Avoid swinging — control the movement", "Curl the pelvis slightly at the top"],
    commonMistakes: ["Using momentum to swing the legs up"],
    alternativeExerciseIds: ["ex_lying_leg_raise", "ex_cable_crunch"],
  }),
  ex({
    id: "ex_plank",
    name: "Plank",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "bodyweight",
    repUnit: "seconds",
    repRangeMin: 30,
    repRangeMax: 60,
    recommendedSets: 3,
    restSeconds: 45,
    instructions: "Forearms and toes on the floor, hold a straight line from head to heels for the target time.",
    formCues: ["Squeeze glutes and brace abs", "Don't let hips sag or pike up"],
    commonMistakes: ["Sagging hips toward the floor", "Holding your breath"],
    alternativeExerciseIds: ["ex_cable_crunch"],
  }),
  ex({
    id: "ex_lying_leg_raise",
    name: "Lying Leg Raise",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    movementType: "isolation",
    isCompound: false,
    level: "beginner",
    loadType: "bodyweight",
    repRangeMin: 10,
    repRangeMax: 15,
    recommendedSets: 3,
    restSeconds: 60,
    instructions: "Lying on your back, legs straight, raise them up toward vertical using your lower abs, lower with control without touching the floor.",
    formCues: ["Press your lower back into the floor", "Control the descent, don't let legs drop"],
    commonMistakes: ["Arching the lower back off the floor"],
    alternativeExerciseIds: ["ex_hanging_leg_raise", "ex_cable_crunch"],
  }),

  // ---------------- CARDIO ----------------
  ex({
    id: "ex_treadmill_walk",
    name: "Treadmill (Incline Walk / Jog)",
    primaryMuscle: "full_body",
    secondaryMuscles: ["quads", "calves"],
    equipment: ["treadmill"],
    movementType: "cardio",
    isCompound: true,
    level: "beginner",
    loadType: "cardio",
    repUnit: "minutes",
    repRangeMin: 15,
    repRangeMax: 25,
    recommendedSets: 1,
    restSeconds: 0,
    instructions: "Walk or jog at a steady pace, optionally with an incline, for the target duration to build aerobic capacity and support fat loss through overall energy expenditure.",
    formCues: ["Keep an upright posture, don't lean on the rails", "Pick a pace you can sustain for the full duration"],
    commonMistakes: ["Holding onto the rails, which reduces effort and calorie expenditure"],
    alternativeExerciseIds: ["ex_exercise_bike"],
  }),
  ex({
    id: "ex_exercise_bike",
    name: "Exercise Bike",
    primaryMuscle: "full_body",
    secondaryMuscles: ["quads", "hamstrings"],
    equipment: ["exercise_bike"],
    movementType: "cardio",
    isCompound: true,
    level: "beginner",
    loadType: "cardio",
    repUnit: "minutes",
    repRangeMin: 15,
    repRangeMax: 25,
    recommendedSets: 1,
    restSeconds: 0,
    instructions: "Cycle at a steady or intervaled pace for the target duration, adjusting resistance to keep effort at a moderate-to-challenging level.",
    formCues: ["Adjust seat height so knees have a slight bend at full extension"],
    commonMistakes: ["Seat too low, causing unnecessary knee strain"],
    alternativeExerciseIds: ["ex_treadmill_walk"],
  }),
];
